### ISSUE TITLE
Register this package with bower?

### ISSUE THREAD

**Issue by adam-knights** [mildrenben/surface#11]
It would be great if we could install and manage this in bower along the lines of `"i-am-surface": 1.0.1`. 

It would also be great to get a new release with all your recent commits.

**Comment by mildrenben** [comment]
@adam-knights I unfortunately do not have the time right now, maybe you could make a pull request?

**Comment by alexey-m-ukolov** [comment]
Just so you know, you can do this:
`bower install mildrenben/surface`
It will install everything that is currently in the master branch.
Same for npm: `npm install mildrenben/surface`
If you need something specific just add it's hash after #.

**Comment by raphaelsoul** [comment]
For my side there is no need to register to npm or bower, (unless you want this project known by more people).
Cause now these two package tools have better support for non-register library on github. just like @alexey-m-ukolov shows, use
```
bower install mildrenben/surface
npm install mildrenben/surface
```

I like surface cause it is very **clear and light**. It is very easy to controll  or overwrite  almost everything.
It is very ideal as a basic  pure css framework
