### ISSUE TITLE
Grid system not working because of classes order

### ISSUE THREAD

**Issue by krem06** [mildrenben/surface#14]
Hi there,

Great little css framework ! I am trying to use it on a personal project but went through a problem regarding the order of classes after sass compilation... The loop in grid.scss was messing up with the normal behaviour so I changed a bit the code so it get the classes order right...

Now everything works fine but I am not sure to understand what is the logic behind the loop to order classes... The problem may even be related to my sass version but in the end the order is right and the grid system works !

Replace the @for in grid.scss by the following code:

```
// Main classes
@for $i from 1 through $grid-columns {
    .g--#{$i} {
        width: 100%/$grid-columns*$i;
        margin-top: $space-big;
        margin-bottom: $space-big;
    }
    .m--#{$i} {
        margin-left: 100%/$grid-columns*$i;
    }
}

// Media queries margin classes - Using while we invert the ordering which was problematic
$j: $grid-columns;
@while $j > 0 {
    @media screen and (max-width: $media-med) {
        .m-m--#{$j} {
            margin-left: 100%/$grid-columns*$j;
        }
    }
    @media screen and (max-width: $media-small) {
        .m-s--#{$j} {
            margin-left: 100%/$grid-columns*$j;

        }
    }
    @media screen and (max-width: $media-tiny) {
        .m-t--#{$j} {
            margin-left: 100%/$grid-columns*$j;
        }
    }
    $j: $j - 1;
}

// Media queries width classes
@for $k from 1 through $grid-columns {
    @media screen and (max-width: $media-med) {
        .g-m--#{$k} {
            width: 100%/$grid-columns*$k;
            margin-top: $space-med*1.3;
            margin-bottom: $space-med*1.3;
        }
    }
    @media screen and (max-width: $media-small) {
        .g-s--#{$k} {
            width: 100%/$grid-columns*$k;
            margin-top: $space-med*0.9;
            margin-bottom: $space-med*0.9;
        }
    }
    @media screen and (max-width: $media-tiny) {
        .g-t--#{$k} {
            width: 100%/$grid-columns*$k;
            margin-top: $space-small;
            margin-bottom: $space-small;
        }
    }
}
```

I don't know if my code is relevant but wanted to share in case ;) 

Thank you for this great framework, bye

**Comment by mildrenben** [comment]
Hey @krem06 :) I noticed there were some issues with the ordering of the grid classes when building this, but it was tough to fix them without using JS (which I didn't use any of).

You're solution seems quite elegant, what exact issues were you having with the ordering of the classes?

**Comment by jackens** [comment]
Consider following HTML:

```html
<div class="g--12 container container--wrap no-margin">
  <div id="item-1" class="g--3 g-m--4 g-s--5 g-t--6 no-margin">[…]</div>
  <div id="item2" class="g--9 g-m--8 g-s--7 g-t--6 no-margin">[…]</div>
</div>
```

For the item-1 browser will use class:

* `g--3` if `$media-med` < screen width
* `g--4` if `$media-small` < screen width <= `$media-med`
* `g--5` if `$media-tiny` < screen width <= `$media-small`
* `g--6` if screen width <= `$media-tiny`.

Just as as expected.
But for `item-2` class `g--9` will be used allways since `g--9` is declared after classes `g-m--8`, `g-s--7` and `g-t--6` in the file `surface_styles.css`.

**Comment by mildrenben** [comment]
This issue has been fixed by @jackens Thank you!
