### ISSUE TITLE
Please add this to bower

### ISSUE THREAD

**Issue by Udokah** [mildrenben/surface#16]
I would like to fork it and add my fork to bower

**Comment by mildrenben** [comment]
@andela-unkwocha I unfortunately do not have the time right now, maybe you could make a pull request?

**Comment by alexey-m-ukolov** [comment]
https://github.com/mildrenben/surface/issues/11#issuecomment-195303260

**Comment by whatisgravity** [comment]
This is a duplicate: https://github.com/mildrenben/surface/issues/11

Should really combine these two.
