### ISSUE TITLE
alert component

### ISSUE THREAD

**Issue by Bandito11** [mildrenben/surface#17]
When creating an alert component the background is the same color as the one used in the body. Had to use a background-color next to the .alert-wrap to fix it.

**Comment by mildrenben** [comment]
@Bandito11 Naturally, Alerts should be either a Tile or a Card and thus should have .tile or .card class as well as the .alert. The tile and the card classes have background colors. 

If you don't want a tile or card alert, then yes you will have to supply a background color via a different class or simply add it to the .alert class. Thanks for the input 👍
