### ISSUE TITLE
Fix button selector specificity

### ISSUE THREAD

**Issue by pigulla** [mildrenben/surface#18]
Currently, the selector for buttons is
```
[class*="btn"]
```
which also matches buttons from other modules that prefix their elements, e.g. [react-widgets](https://github.com/jquense/react-widgets) which uses the `rw-` prefix.

This is unnecessary, the selector
```
[class^="btn"]
```
would be preferrable.

**Comment by mildrenben** [comment]
Merging your request. Thanks :+1:
