### ISSUE TITLE
Site Issues

### ISSUE THREAD

**Issue by grantcarthew** [mildrenben/surface#2]
Hey,
On your site there are two issues I saw.
The grid page has;
.container--baseline - This class aligns elements so that the text baselines align
.container--center - This class aligns elements centrally
.container--baseline - This class aligns elements at the top of the container
.container--baseline - This class aligns elements at the bottom of the container

Also, the vertical menu on the side is responsive which destroys the nav component responsive interface.

It looks really great. I love the CSS only take.
Why all the -- in the names. Not sure I like the class names but I am no expert.

Regards.

**Comment by mildrenben** [comment]
Changed the dupicates of container class names. And I'll look into the responsive nav thing. Thanks for the heads up.

The double dash name convention comes from BEM.
