### ISSUE TITLE
Helper classes for showing/hiding in breakpoints

### ISSUE THREAD

**Issue by go4cas** [mildrenben/surface#22]
Would be cool to include some helpers to show/hide elements on certain breakpoints - similar to what Material Design Lite does [here](https://getmdl.io/components/index.html#layout-section) with the `mdl-cell--hide-desktop`, `mdl-cell--hide-tablet`, etc.

**Comment by mildrenben** [comment]
Glad you like Surface but I will not be updating this framework (besides minor fixes). If you'd like to do this yourself and submit a PR feel free 👍
