### ISSUE TITLE
Responsive tables

### ISSUE THREAD

**Issue by whatisgravity** [mildrenben/surface#23]
Would there be interest in taking a patch for responsive tables. Essentially for mobile the tables are reoriented so they fit the decreased width.

Here is a very basic CSS only example: file:///home/user/Desktop/responsive-table-using-css/table-responsive-using-css.html

Edit: I also found 26 letters done in css, so combined with color boxes, the material avatar system could be impleneted in CSS only too.

**Comment by mildrenben** [comment]
Hi @whatisgravity . You have linked a local file and I cannot see what you're referring to, could you possibly post the code somewhere online?
