### ISSUE TITLE
`input` element must have a `type` attribute

### ISSUE THREAD

**Issue by eirikb** [mildrenben/surface#28]
Hi

Input elements must have `type` attribute set, e.g., 

```
<input type="text">
```

even though `type="text"` is default.  
This can be fixed by adding `>&` to _forms.scss_.
I have decided to not make a PR since I'm not sure if this is a good idea.

**Comment by mildrenben** [comment]
Glad you like Surface but I will not be updating this framework (besides minor fixes). If you'd like to do this yourself and submit a PR feel free 👍
