### ISSUE TITLE
Request to theme textarea based on MDL guidelines

### ISSUE THREAD

**Issue by zakaluka** [mildrenben/surface#30]
Here is a link (https://material.google.com/components/text-fields.html#text-fields-multi-line-text-field) to the MDL guidelines on textareas.  

I would like to ask whether there is a plan in place to theme textareas based on the guidance provided there.  If not, would you be willing to accept a PR to do so?

**Comment by mildrenben** [comment]
Hi there,

Unfortunately, I do not really have the time to dedicate to things like this, but I'm be more than happy to accept a PR :)

Cheers
