### ISSUE TITLE
AMP support

### ISSUE THREAD

**Issue by niutech** [mildrenben/surface#40]
Your CSS-only framework is very useful for building AMP pages. I made the [demo](http://jsbin.com/xohugojufe/) which is a valid AMP HTML, although I had to remove the `@charset` and `!important` statements. Would you like to create an official AMP version of your fantastic framework? Would you provide a valid output CSS to copy?

**Comment by mildrenben** [comment]
Glad you like Surface but I will not be updating this framework (besides minor fixes). If you'd like to do this yourself and submit a PR feel free 👍

**Comment by KiaraGrouwstra** [comment]
I've put up a PR based on @niutech's suggestion at #44.

**Comment by niutech** [comment]
Thanks @tycho01!

**Comment by niutech** [comment]
Finally I have made an AMP version of Surface, by removing illegal CSS and replacing illegal HTML tags: https://github.com/niutech/amp-surface/
