### ISSUE TITLE
collapsibles component bug?

### ISSUE THREAD

**Issue by xi3** [mildrenben/surface#9]
http://www.iamsurface.com/docs/collapsibles.html

chrome on win64, if click many times of collapsibles, strange cover apperead is below:

https://docs.google.com/file/d/0B8wUYSBo5qdKeGFRTGpxQU1CQlE/edit?usp=drivesdk

**Comment by mildrenben** [comment]
That's just highlighting the collapsible label, not sure if there is anything that can be done in CSS about that
